### ISSUE TITLE
panda doodle does not work offline

### ISSUE THREAD

**Issue by pickfire** [lucamoller/pandadoodle-rust-wasm#3]
It would be cool that maybe it can use service worker or such such that even when offline the game is still playable.

**Comment by lucamoller** [comment]
Hi Ivan,

On Android, I do use service workers to make the game available offline, I've just checked on my phone it seems to be working.

On iOS on the other hand, I did have service workers to make it available offline at first, but then that was causing issues with the audio APIs (iOS Safari is just a big mess and has a bunch of arbitrary behaviors) when they were fetching audio resources, so I had to disable it (see https://github.com/lucamoller/pandadoodle-rust-wasm/blob/main/html/index.html#L109)

Are you running the game on iOS or on Android?

**Comment by pickfire** [comment]
Sorry, I didn't give enough context.

I am running it on android, through firefox 94.1 (fenix), I also tried adding the website to home screen but it still doesn't work. Is it because I use firefox?

I load it first, then disable the network, close the browser (or the application added to home screen), then start it again, it didn't load.

**Comment by pickfire** [comment]
This seemed to work now.
